// category는 사회적 목적 유형 (ex. 일자리제공형, 지역사회공헌형 등)
// businessType는 사업 유형 (ex. 음식점, 쇼핑, 카페 등)
// 거리와 리뷰 수는 임시 값 넣음

const samplePlaces = [
  {
    id: 1,
    name: "사회적협동조합 바른",
    category: "사회서비스제공형",
    businessType: "기타",
    description:
      "장애인의 든든한 동반자, 존중 받는 활동지원사, 장애인이 살기 좋은 지역문화 형성을 위해 노력합니다.",
    distance: "541m",
    review: "방문자 리뷰 27",
    address: "서울특별시 양천구 공항대로 552 (목동) 1층 105호(목동대우마이빌)",
    homepage: "www.balun.or.kr",
    phone: "02-2645-6060",
    images: ["/images/sample1.jpeg"],
    liked: false,
    coords: { lat: 37.544331, lng: 126.8668498 },
  },
  {
    id: 2,
    name: "(주)신호에이피엘",
    category: "일자리제공형",
    businessType: "쇼핑",
    description:
      "30여년 동안 유니폼(티셔츠/자켓/남방/앞치마/작업복 등)을 전문적으로 디자인하여 직접 제조·생산하는 전문기업입니다.",
    distance: "541m",
    review: "방문자 리뷰 27",
    address:
      "서울특별시 중랑구 신내역로 111 , 423호, 424호(신내동, 신내에스케이브이1센터)",
    homepage: "www.tmaeul.co.kr",
    phone: "02-2214-8115",
    images: ["/images/sample3.jpeg"],
    liked: false,
    coords: { lat: 37.6131395, lng: 127.1124178 },
  },
  {
    id: 3,
    name: "행복도시락사회적협동조합",
    category: "지역사회공헌형",
    businessType: "음식점",
    description:
      "결식이웃지원 도시락 사업을 통해 공공급식 사회서비스의 품질 개선과 양극화 해소, 근로빈곤층의 빈곤 완화를 위한 지속 가능한 일자리를 창출합니다.",
    distance: "541m",
    review: "방문자 리뷰 27",
    address: "서울특별시 용산구 독서당로 46 (한남동, 한남아이파크) 비1층",
    homepage: "http://happydosirak.org",
    phone: "02-6010-6100",
    images: ["/images/sample4.jpeg"],
    liked: false,
    coords: { lat: 37.5323909, lng: 127.0072568 },
  },
  {
    id: 4,
    name: "주식회사 카페티모르",
    category: "일자리제공형",
    businessType: "카페",
    description:
      "동티모르 커피 생산자 지원과 바리스타 직업훈련을 통해 공정무역 확산과 청년 일자리 창출에 기여하고 있습니다.",
    address: "서울특별시 영등포구 당산로16길 9(당산동 1가)",
    homepage: "www.peacecoffee.co.kr",
    phone: "02-365-7891",
    coords: { lat: 37.5199833, lng: 126.8992604 },
    liked: false,
    distance: "500m",
    review: "방문자 리뷰 12",
    images: ["/images/sample1.jpeg", "/images/sample2.jpeg"],
  },
  {
    id: 5,
    name: "사단법인 캔파운데이션",
    category: "기타(창의ㆍ혁신)형",
    businessType: "문화/예술",
    description:
      "예술 창작 지원과 해외 교류를 통해 작가 발굴과 문화 확산을 추진하며, 미술계의 공익성과 사회적 연대를 강화합니다.",
    address: "서울특별시 용산구 이태원로27길 101 (한남동) 1층",
    homepage: "www.can-foundation.org",
    phone: "02-766-7660",
    coords: { lat: 37.5377778, lng: 126.9949691 },
    liked: false,
    distance: "600m",
    review: "방문자 리뷰 9",
    images: ["/images/sample3.jpeg", "/images/sample4.jpeg"],
  },
  {
    id: 6,
    name: "언더독스주식회사",
    category: "기타(창의ㆍ혁신)형",
    businessType: "교육/지원",
    description:
      "창업가들이 만들어갈 미래의 변화를 앞당기기 위해 창업가의 시작을 돕는 파트너로 함께합니다. 창업가가 추구하는 가치가 원활히 구현될 수 있도록 새로운 기회를 제공하고 실행 중심 교육을 통해 성장을 이끌어냅니다.",
    address: "서울특별시 종로구 돈화문로 88-1(와룡동) UD빌딩 401호",
    homepage: "https://underdogs.co.kr/",
    phone: "02-6384-3222",
    coords: { lat: 37.5763751, lng: 126.990555 },
    liked: false,
    distance: "720m",
    review: "방문자 리뷰 14",
    images: ["/images/sample1.jpeg", "/images/sample2.jpeg"],
  },
  {
    id: 7,
    name: "책농장",
    category: "기타(창의ㆍ혁신)형",
    businessType: "기타",
    description:
      "언제 어디서나 책을 가까이하는 사회 만들기에 노력하고 있습니다.",
    address: "서울특별시 서대문구 신촌로 169(대현동)",
    homepage: "www.webookfarm.com",
    phone: "070-4036-9732",
    coords: { lat: 37.5604123, lng: 126.9463132 },
    liked: false,
    distance: "610m",
    review: "방문자 리뷰 7",
    images: ["/images/sample3.jpeg", "/images/sample4.jpeg"],
  },
];

export default samplePlaces;
