export const districtOptions = [
  { value: "강남구", label: "강남구" },
  { value: "강동구", label: "강동구" },
  { value: "강북구", label: "강북구" },
  { value: "강서구", label: "강서구" },
  { value: "관악구", label: "관악구" },
  { value: "광진구", label: "광진구" },
  { value: "구로구", label: "구로구" },
  { value: "금천구", label: "금천구" },
  { value: "노원구", label: "노원구" },
  { value: "도봉구", label: "도봉구" },
  { value: "동대문구", label: "동대문구" },
  { value: "동작구", label: "동작구" },
  { value: "마포구", label: "마포구" },
  { value: "서대문구", label: "서대문구" },
  { value: "서초구", label: "서초구" },
  { value: "성동구", label: "성동구" },
  { value: "성북구", label: "성북구" },
  { value: "송파구", label: "송파구" },
  { value: "양천구", label: "양천구" },
  { value: "영등포구", label: "영등포구" },
  { value: "용산구", label: "용산구" },
  { value: "은평구", label: "은평구" },
  { value: "종로구", label: "종로구" },
  { value: "중구", label: "중구" },
  { value: "중랑구", label: "중랑구" },
];

export const unitOptions = {
  강남구: [
    { value: "개포동", label: "개포동" },
    { value: "논현동", label: "논현동" },
    { value: "대치동", label: "대치동" },
    { value: "도곡동", label: "도곡동" },
    { value: "삼성동", label: "삼성동" },
    { value: "세곡동", label: "세곡동" },
    { value: "수서동", label: "수서동" },
    { value: "신사동", label: "신사동" },
    { value: "압구정동", label: "압구정동" },
    { value: "역삼동", label: "역삼동" },
    { value: "율현동", label: "율현동" },
    { value: "일원동", label: "일원동" },
    { value: "자곡동", label: "자곡동" },
    { value: "청담동", label: "청담동" },
  ],
  강동구: [
    { value: "강일동", label: "강일동" },
    { value: "고덕동", label: "고덕동" },
    { value: "길동", label: "길동" },
    { value: "둔촌동", label: "둔촌동" },
    { value: "명일동", label: "명일동" },
    { value: "상일동", label: "상일동" },
    { value: "성내동", label: "성내동" },
    { value: "암사동", label: "암사동" },
    { value: "천호동", label: "천호동" },
  ],
  강북구: [
    { value: "미아동", label: "미아동" },
    { value: "번동", label: "번동" },
    { value: "수유동", label: "수유동" },
    { value: "우이동", label: "우이동" },
  ],
  강서구: [
    { value: "가양동", label: "가양동" },
    { value: "개화동", label: "개화동" },
    { value: "공항동", label: "공항동" },
    { value: "과해동", label: "과해동" },
    { value: "내발산동", label: "내발산동" },
    { value: "등촌동", label: "등촌동" },
    { value: "마곡동", label: "마곡동" },
    { value: "방화동", label: "방화동" },
    { value: "외발산동", label: "외발산동" },
    { value: "오곡동", label: "오곡동" },
    { value: "오쇠동", label: "오쇠동" },
    { value: "염창동", label: "염창동" },
    { value: "화곡동", label: "화곡동" },
  ],
  관악구: [
    { value: "남현동", label: "남현동" },
    { value: "봉천동", label: "봉천동" },
    { value: "신림동", label: "신림동" },
  ],
};
